class FieldDefinitions {
  static List<Map<String, dynamic>> fallbackFor(String tableDestino) {
    return (fallback[tableDestino] ?? const <Map<String, dynamic>>[])
        .map((e) => Map<String, dynamic>.from(e))
        .toList();
  }

  static const Map<String, List<Map<String, dynamic>>> fallback = {
    'SIG-EVALUACION_PROCESOS_BARRA': [
      {'campo': 'ID_REGISTRO', 'etiqueta': 'ID Registro', 'tipo': 'hidden_id', 'requerido': 1, 'orden': 1},
      {'campo': 'FECHA', 'etiqueta': 'Fecha', 'tipo': 'date', 'requerido': 1, 'orden': 2},
      {'campo': 'TURNO', 'etiqueta': 'Turno', 'tipo': 'text', 'requerido': 0, 'orden': 3},
      {'campo': 'INSPECCION DE MAQUINARIA DE APLICACION', 'etiqueta': 'Inspección de maquinaria de aplicación', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 4},
      {'campo': 'ABASTECIMIENTO DE COMBUSTIBLE COMPLETO', 'etiqueta': 'Abastecimiento de combustible completo', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 5},
      {'campo': 'EQUIPO DE PROTECCION PERSONAL', 'etiqueta': 'Equipo de protección personal', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 6},
      {'campo': 'ACCESORIOS', 'etiqueta': 'Accesorios', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 7},
      {'campo': 'EQUIPO DE PROTECCION PERSONAL PERSONAL', 'etiqueta': 'EPP personal', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 8},
      {'campo': 'EQUIPO DE PROTECCION PERSONAL SUPERVISOR', 'etiqueta': 'EPP supervisor', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 9},
      {'campo': 'APROVECHAMIENTO DEL PRODUCTO', 'etiqueta': 'Aprovechamiento del producto', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 10},
      {'campo': 'REVISION ORDENES DE APLICACION', 'etiqueta': 'Revisión órdenes de aplicación', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 11},
      {'campo': 'INSTRUCTIVO DE BOQUILLAS', 'etiqueta': 'Instructivo de boquillas', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 12},
      {'campo': 'ORDEN DE PREMEZCLA', 'etiqueta': 'Orden de premezcla', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 13},
      {'campo': 'CORRECTA DISOLUCION DEL PRODUCTO', 'etiqueta': 'Correcta disolución del producto', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 14},
      {'campo': 'EQUIPO DE PROTECCIÓN PERSONAL PERSONAL2', 'etiqueta': 'EPP personal 2', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 15},
      {'campo': 'EQUIPO DE PROTECCIÓN PERSONAL SUPERVISOR2', 'etiqueta': 'EPP supervisor 2', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 16},
      {'campo': 'AGITACIO DE LOS PRODUCTOS', 'etiqueta': 'Agitación de los productos', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 17},
      {'campo': 'REVISION DE BOQUILLAS', 'etiqueta': 'Revisión de boquillas', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 18},
      {'campo': 'COLOCACION Y RETIRO DE BANDERINES DE PELIGRO', 'etiqueta': 'Colocación y retiro de banderines de peligro', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 19},
      {'campo': 'OBSERVACIONES', 'etiqueta': 'Observaciones', 'tipo': 'multiline', 'requerido': 0, 'orden': 20},
      {'campo': 'SUPERVISOR', 'etiqueta': 'Supervisor', 'tipo': 'text', 'requerido': 0, 'orden': 21},
      {'campo': 'FIRMA DEL SUPERVISOR', 'etiqueta': 'Firma del supervisor', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 22},
      {'campo': 'JEFE DEL AREA', 'etiqueta': 'Jefe del área', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 23},
      {'campo': 'FIRMA DEL JEFE', 'etiqueta': 'Firma del jefe', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 24},
    ],
    'SIG-EVALUACION_PROCESOS_DESPACHO_PREMEZCLA': [
      {'campo': 'ID_REGISTRO', 'etiqueta': 'ID Registro', 'tipo': 'hidden_id', 'requerido': 1, 'orden': 1},
      {'campo': 'FECHA', 'etiqueta': 'Fecha', 'tipo': 'date', 'requerido': 1, 'orden': 2},
      {'campo': 'TURNO', 'etiqueta': 'Turno', 'tipo': 'text', 'requerido': 0, 'orden': 3},
      {'campo': 'MAQUINARIA', 'etiqueta': 'Maquinaria', 'tipo': 'text', 'requerido': 0, 'orden': 4},
      {'campo': 'ORDEN Y LIMPIEZA', 'etiqueta': 'Orden y limpieza', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 5},
      {'campo': 'USO DE EPPs', 'etiqueta': 'Uso de EPPs', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 6},
      {'campo': 'LAVADO DE EPPs', 'etiqueta': 'Lavado de EPPs', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 7},
      {'campo': 'CARTILLA_ORDEN DE APLICACION_VALE', 'etiqueta': 'Cartilla / orden de aplicación / vale', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 8},
      {'campo': 'PROCESO DE DESPACHO', 'etiqueta': 'Proceso de despacho', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 9},
      {'campo': 'CORROBORACION DE PRODUCTOS', 'etiqueta': 'Corroboración de productos', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 10},
      {'campo': 'SALIDA DE PRODUCTO', 'etiqueta': 'Salida de producto', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 11},
      {'campo': 'LAVADO DE MATERIALES DE PREMEZCLA', 'etiqueta': 'Lavado de materiales de premezcla', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 12},
      {'campo': 'ENVASES PARA PRODUCTO PREMEZCLADO', 'etiqueta': 'Envases para producto premezclado', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 13},
      {'campo': 'RETORNO DE ENVASES VACIOS', 'etiqueta': 'Retorno de envases vacíos', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 14},
      {'campo': 'OBSERVACIONES', 'etiqueta': 'Observaciones', 'tipo': 'multiline', 'requerido': 0, 'orden': 15},
      {'campo': 'SUPERVISOR', 'etiqueta': 'Supervisor', 'tipo': 'text', 'requerido': 0, 'orden': 16},
      {'campo': 'FIRMA DEL SUPERVISOR', 'etiqueta': 'Firma del supervisor', 'tipo': 'text', 'requerido': 0, 'orden': 17},
      {'campo': 'JEFE DEL AREA', 'etiqueta': 'Jefe del área', 'tipo': 'text', 'requerido': 0, 'orden': 18},
      {'campo': 'FIRMA DEL JEFE', 'etiqueta': 'Firma del jefe', 'tipo': 'text', 'requerido': 0, 'orden': 19},
    ],
    'SIG-EVALUACION_PROCESOS_OBSERVACIONES': [
      {'campo': 'id', 'etiqueta': 'ID Registro', 'tipo': 'hidden_id', 'requerido': 1, 'orden': 1},
      {'campo': 'FECHA', 'etiqueta': 'Fecha', 'tipo': 'date', 'requerido': 1, 'orden': 2},
      {'campo': 'TURNO', 'etiqueta': 'Turno', 'tipo': 'text', 'requerido': 0, 'orden': 3},
      {'campo': 'TIPO. MAQUINARIA', 'etiqueta': 'Tipo maquinaria', 'tipo': 'text', 'requerido': 0, 'orden': 4},
      {'campo': 'ACTIVIDAD', 'etiqueta': 'Actividad', 'tipo': 'text', 'requerido': 0, 'orden': 5},
      {'campo': 'ITEM_ACTIVIDAD', 'etiqueta': 'Item actividad', 'tipo': 'text', 'requerido': 0, 'orden': 6},
      {'campo': 'OBSERVACIONES', 'etiqueta': 'Observaciones', 'tipo': 'multiline', 'requerido': 0, 'orden': 7},
    ],
    'SIG-EVALUACION_PROCESOS_TIZONA': [
      {'campo': 'ID_REGISTRO', 'etiqueta': 'ID Registro', 'tipo': 'hidden_id', 'requerido': 1, 'orden': 1},
      {'campo': 'FECHA', 'etiqueta': 'Fecha', 'tipo': 'date', 'requerido': 1, 'orden': 2},
      {'campo': 'TURNO', 'etiqueta': 'Turno', 'tipo': 'text', 'requerido': 0, 'orden': 3},
      {'campo': 'INSPECCION DE MAQUINARIA DE APLICACION', 'etiqueta': 'Inspección de maquinaria de aplicación', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 4},
      {'campo': 'ABASTECIMIENTO DE COMBUSTIBLE COMPLETO', 'etiqueta': 'Abastecimiento de combustible completo', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 5},
      {'campo': 'EQUIPO DE PROTECCION PERSONAL', 'etiqueta': 'Equipo de protección personal', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 6},
      {'campo': 'ACCESORIOS', 'etiqueta': 'Accesorios', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 7},
      {'campo': 'EQUIPO DE PROTECCION PERSONAL PERSONAL', 'etiqueta': 'EPP personal', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 8},
      {'campo': 'EQUIPO DE PROTECCION PERSONAL SUPERVISOR', 'etiqueta': 'EPP supervisor', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 9},
      {'campo': 'APROVECHAMIENTO DEL PRODUCTO', 'etiqueta': 'Aprovechamiento del producto', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 10},
      {'campo': 'REVISION ORDENES DE APLICACION', 'etiqueta': 'Revisión órdenes de aplicación', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 11},
      {'campo': 'INSTRUCTIVO DE BOQUILLAS', 'etiqueta': 'Instructivo de boquillas', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 12},
      {'campo': 'ORDEN DE PREMEZCLA', 'etiqueta': 'Orden de premezcla', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 13},
      {'campo': 'CORRECTA DISOLUCION DEL PRODUCTO', 'etiqueta': 'Correcta disolución del producto', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 14},
      {'campo': 'EQUIPO DE PROTECCIÓN PERSONAL PERSONAL2', 'etiqueta': 'EPP personal 2', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 15},
      {'campo': 'EQUIPO DE PROTECCIÓN PERSONAL SUPERVISOR2', 'etiqueta': 'EPP supervisor 2', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 16},
      {'campo': 'AGITACIÓN DE LOS PRODUCTOS', 'etiqueta': 'Agitación de los productos', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 17},
      {'campo': 'REVISION DE BOQUILLAS', 'etiqueta': 'Revisión de boquillas', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 18},
      {'campo': 'REVISION DEL CAMINO(COMIENZO O DURANTE EL PROCESO DE APLICACIÓ', 'etiqueta': 'Revisión del camino', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 19},
      {'campo': 'COLOCACIÓN Y RETIRO DE BANDERINES DE PELIGRO', 'etiqueta': 'Colocación y retiro de banderines de peligro', 'tipo': 'boolean_int', 'requerido': 0, 'orden': 20},
      {'campo': 'OBSERVACIONES', 'etiqueta': 'Observaciones', 'tipo': 'multiline', 'requerido': 0, 'orden': 21},
      {'campo': 'SUPERVISOR', 'etiqueta': 'Supervisor', 'tipo': 'text', 'requerido': 0, 'orden': 22},
      {'campo': 'FIRMA DEL SUPERVISOR', 'etiqueta': 'Firma del supervisor', 'tipo': 'text', 'requerido': 0, 'orden': 23},
      {'campo': 'JEFE DEL AREA', 'etiqueta': 'Jefe del área', 'tipo': 'text', 'requerido': 0, 'orden': 24},
      {'campo': 'FIRMA DEL JEFE', 'etiqueta': 'Firma del jefe', 'tipo': 'text', 'requerido': 0, 'orden': 25},
    ],
  };
}
